version: '3'
services:
  selenium-standalone:
    image: selenium/standalone:latest  # The standalone image supports both Chrome and Firefox
    container_name: selenium-standalone
    ports:
      - "4444:4444"  # Exposes the Selenium Grid port
    environment:
      - SE_NODE_MAX_SESSIONS=5         # Maximum number of parallel sessions
      - SE_NODE_SESSION_TIMEOUT=60     # Session timeout in seconds
    platform: linux/amd64              # Ensures compatibility on M1/M2 Mac
    networks:
      - selenium-grid-network

networks:
  selenium-grid-network:
    driver: bridge